
GET http://localhost:3000/api/courses

###

GET http://localhost:3000/api/courses/1

###

POST http://localhost:3000/api/courses
Content-Type: application/json

### 

PUT http://localhost:3000/api/courses/1
Content-Type: application/json 

{
    "name": "Nytt namn på kursen5", 
    "points": "100", 
    "location": "Ny plats"
}

###

DELETE http://localhost:3000/api/courses/10

###